name = "haoai-platform"
compatibility_date = "2024-04-01"
account_id = "6ae89ca032e48bfa097d91ca329f7f23"

[[d1_databases]]
binding = "DB"
database_name = "haoai-db"
database_id = "16396199-fe5c-4ad1-abde-f34c8eedbf45"
